//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Redbud.BL.Resources.EmailerResources", typeof(EmailerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},
        ///
        ///Please find attached your credit memo #{1}.
        ///
        ///Please review the credit memo, and contact us if you have any questions..
        /// </summary>
        public static string CreditMemoEmailBody {
            get {
                return ResourceManager.GetString("CreditMemoEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redbud – Credit Memo # {0}.
        /// </summary>
        public static string CreditMemoEmailSubject {
            get {
                return ResourceManager.GetString("CreditMemoEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;https://www.redbud.com&apos;&gt;Login to the Redbud.com to view and manage your account.&lt;/a&gt;
        ///
        ///Sincerely,
        ///The Redbud Admin Team
        ///&lt;img src=&quot;https://catch.redbud.com/img/Redbud_email.jpg&quot; /&gt;
        ///tel: &lt;a href=&apos;tel:1.888.733.2830&apos;&gt;1.888.733.2830&lt;/a&gt; / fax: 1.888.733.2850
        ///email: &lt;a href=&apos;mailto:sales@redbud.com&apos;&gt;sales@redbud.com&lt;/a&gt;
        ///website: &lt;a href=&apos;https://www.redbud.com&apos;&gt;www.redbud.com&lt;/a&gt;.
        /// </summary>
        public static string EmailFooter {
            get {
                return ResourceManager.GetString("EmailFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.xls.
        /// </summary>
        public static string EXCELContentType {
            get {
                return ResourceManager.GetString("EXCELContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},
        ///
        ///A request was received to send your login information for the Redbud website. Your login information is as follows:
        ///
        ///Email address: {1}
        ///Password: {2}
        ///
        ///Once you gain access to the website, you may change your password by clicking on Change Password under the My Account tab..
        /// </summary>
        public static string ForgetPasswordEmail {
            get {
                return ResourceManager.GetString("ForgetPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redbud – Your login information for the Redbud.com.
        /// </summary>
        public static string ForgetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ForgetPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},
        ///
        ///Thank you for choosing Redbud.
        ///
        ///We have received your recent order submission (Order #{1}). You will receive a detailed order confirmation once we have processed your order. In the meantime, please contact us if you have any questions..
        /// </summary>
        public static string OnlineOrderSubmissionBody {
            get {
                return ResourceManager.GetString("OnlineOrderSubmissionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onlineorders@redbud.com.
        /// </summary>
        public static string OnlineOrderSubmissionCc {
            get {
                return ResourceManager.GetString("OnlineOrderSubmissionCc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redbud – Online order submission.
        /// </summary>
        public static string OnlineOrderSubmissionSubject {
            get {
                return ResourceManager.GetString("OnlineOrderSubmissionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},
        ///
        ///Please find attached your detailed order confirmation for Order  #{1}.
        ///
        ///Please review the order and shipping date, and contact us if you have any questions.
        ///
        ///.
        /// </summary>
        public static string OrderConfirmationEmailBody {
            get {
                return ResourceManager.GetString("OrderConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redbud – Order confirmation for Order # {0}.
        /// </summary>
        public static string OrderConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("OrderConfirmationEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},
        ///
        ///Please find attached the packing slip for Shipment #{1}.
        ///
        ///If you require a more detailed tracking, please contact our office.
        ///.
        /// </summary>
        public static string PackingSlipEmailBody {
            get {
                return ResourceManager.GetString("PackingSlipEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redbud – Packing slip for Shipment # {0}.
        /// </summary>
        public static string PackingSlipEmailSubject {
            get {
                return ResourceManager.GetString("PackingSlipEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pdf.
        /// </summary>
        public static string PDFContentType {
            get {
                return ResourceManager.GetString("PDFContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PickSheetEmailBody {
            get {
                return ResourceManager.GetString("PickSheetEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redbud – Pick sheet for Order# {0}.
        /// </summary>
        public static string PickSheetEmailSubject {
            get {
                return ResourceManager.GetString("PickSheetEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},
        ///
        ///Please find attached the invoice for Shipment #{1}.
        ///
        ///If you have any questions, please contact our office.
        ///.
        /// </summary>
        public static string SendInvoiceEmailBody {
            get {
                return ResourceManager.GetString("SendInvoiceEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redbud – Invoice for Shipment  {0}.
        /// </summary>
        public static string SendInvoiceEmailSubject {
            get {
                return ResourceManager.GetString("SendInvoiceEmailSubject", resourceCulture);
            }
        }
    }
}
