//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Maddux.Catch.wsFCSBugTracker {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IssueReportingServicesSoap", Namespace="http://ws.fortesolutions.ca/")]
    public partial class IssueReportingServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SubmitErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitSuggestionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitApplicationUpdateNotificationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IssueReportingServices() {
            this.Url = "http://ws.fortesolutions.ca/bt/FCSBugTracker.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubmitErrorCompletedEventHandler SubmitErrorCompleted;
        
        /// <remarks/>
        public event SubmitSuggestionCompletedEventHandler SubmitSuggestionCompleted;
        
        /// <remarks/>
        public event SubmitApplicationUpdateNotificationCompletedEventHandler SubmitApplicationUpdateNotificationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.fortesolutions.ca/SubmitError", RequestNamespace="http://ws.fortesolutions.ca/", ResponseNamespace="http://ws.fortesolutions.ca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SubmissionResult[] SubmitError(int applicationID, string userName, string userEmail, string userPhone, string errorDescription, bool sendConfirmation) {
            object[] results = this.Invoke("SubmitError", new object[] {
                        applicationID,
                        userName,
                        userEmail,
                        userPhone,
                        errorDescription,
                        sendConfirmation});
            return ((SubmissionResult[])(results[0]));
        }
        
        /// <remarks/>
        public void SubmitErrorAsync(int applicationID, string userName, string userEmail, string userPhone, string errorDescription, bool sendConfirmation) {
            this.SubmitErrorAsync(applicationID, userName, userEmail, userPhone, errorDescription, sendConfirmation, null);
        }
        
        /// <remarks/>
        public void SubmitErrorAsync(int applicationID, string userName, string userEmail, string userPhone, string errorDescription, bool sendConfirmation, object userState) {
            if ((this.SubmitErrorOperationCompleted == null)) {
                this.SubmitErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitErrorOperationCompleted);
            }
            this.InvokeAsync("SubmitError", new object[] {
                        applicationID,
                        userName,
                        userEmail,
                        userPhone,
                        errorDescription,
                        sendConfirmation}, this.SubmitErrorOperationCompleted, userState);
        }
        
        private void OnSubmitErrorOperationCompleted(object arg) {
            if ((this.SubmitErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitErrorCompleted(this, new SubmitErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.fortesolutions.ca/SubmitSuggestion", RequestNamespace="http://ws.fortesolutions.ca/", ResponseNamespace="http://ws.fortesolutions.ca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SubmissionResult[] SubmitSuggestion(int applicationID, string userName, string userEmail, string userPhone, string suggestionText) {
            object[] results = this.Invoke("SubmitSuggestion", new object[] {
                        applicationID,
                        userName,
                        userEmail,
                        userPhone,
                        suggestionText});
            return ((SubmissionResult[])(results[0]));
        }
        
        /// <remarks/>
        public void SubmitSuggestionAsync(int applicationID, string userName, string userEmail, string userPhone, string suggestionText) {
            this.SubmitSuggestionAsync(applicationID, userName, userEmail, userPhone, suggestionText, null);
        }
        
        /// <remarks/>
        public void SubmitSuggestionAsync(int applicationID, string userName, string userEmail, string userPhone, string suggestionText, object userState) {
            if ((this.SubmitSuggestionOperationCompleted == null)) {
                this.SubmitSuggestionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitSuggestionOperationCompleted);
            }
            this.InvokeAsync("SubmitSuggestion", new object[] {
                        applicationID,
                        userName,
                        userEmail,
                        userPhone,
                        suggestionText}, this.SubmitSuggestionOperationCompleted, userState);
        }
        
        private void OnSubmitSuggestionOperationCompleted(object arg) {
            if ((this.SubmitSuggestionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitSuggestionCompleted(this, new SubmitSuggestionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ws.fortesolutions.ca/SubmitApplicationUpdateNotification", RequestNamespace="http://ws.fortesolutions.ca/", ResponseNamespace="http://ws.fortesolutions.ca/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public SubmissionResult[] SubmitApplicationUpdateNotification(int applicationID, string versionDesc, string customerName) {
            object[] results = this.Invoke("SubmitApplicationUpdateNotification", new object[] {
                        applicationID,
                        versionDesc,
                        customerName});
            return ((SubmissionResult[])(results[0]));
        }
        
        /// <remarks/>
        public void SubmitApplicationUpdateNotificationAsync(int applicationID, string versionDesc, string customerName) {
            this.SubmitApplicationUpdateNotificationAsync(applicationID, versionDesc, customerName, null);
        }
        
        /// <remarks/>
        public void SubmitApplicationUpdateNotificationAsync(int applicationID, string versionDesc, string customerName, object userState) {
            if ((this.SubmitApplicationUpdateNotificationOperationCompleted == null)) {
                this.SubmitApplicationUpdateNotificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitApplicationUpdateNotificationOperationCompleted);
            }
            this.InvokeAsync("SubmitApplicationUpdateNotification", new object[] {
                        applicationID,
                        versionDesc,
                        customerName}, this.SubmitApplicationUpdateNotificationOperationCompleted, userState);
        }
        
        private void OnSubmitApplicationUpdateNotificationOperationCompleted(object arg) {
            if ((this.SubmitApplicationUpdateNotificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitApplicationUpdateNotificationCompleted(this, new SubmitApplicationUpdateNotificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.fortesolutions.ca/")]
    public partial class SubmissionResult {
        
        private int resultCodeField;
        
        private string resultDescriptionField;
        
        /// <remarks/>
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SubmitErrorCompletedEventHandler(object sender, SubmitErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubmissionResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubmissionResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SubmitSuggestionCompletedEventHandler(object sender, SubmitSuggestionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitSuggestionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitSuggestionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubmissionResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubmissionResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SubmitApplicationUpdateNotificationCompletedEventHandler(object sender, SubmitApplicationUpdateNotificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitApplicationUpdateNotificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitApplicationUpdateNotificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SubmissionResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SubmissionResult[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591