//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int ActivityLogId { get; set; }
        public string SessionId { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public int CustomerId { get; set; }
        public string CustomerEmail { get; set; }
        public string PageName { get; set; }
        public string ActivityDesc { get; set; }
        public string Platform { get; set; }
        public string BrowserType { get; set; }
        public string BrowserVersion { get; set; }
        public string IpAddress { get; set; }
    }
}
