//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.Journals = new HashSet<Journal>();
            this.CampaignShipdates = new HashSet<CampaignShipdate>();
        }
    
        public int CampaignID { get; set; }
        public Nullable<System.DateTime> Shipdate { get; set; }
        public System.DateTime SalesStart { get; set; }
        public System.DateTime SalesEnd { get; set; }
        public int Goal { get; set; }
        public int ProgramID { get; set; }
        public string CampaignName { get; set; }
    
        public virtual ProductProgram ProductProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignShipdate> CampaignShipdates { get; set; }
    }
}
