//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditItem
    {
        public int CreditItemId { get; set; }
        public int CreditID { get; set; }
        public double Units { get; set; }
        public double PackagesPerUnit { get; set; }
        public int ProductId { get; set; }
        public decimal EachPrice { get; set; }
    
        public virtual Credit Credit { get; set; }
        public virtual Product Product { get; set; }
    }
}
