//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credit()
        {
            this.CreditItems = new HashSet<CreditItem>();
        }
    
        public int CreditID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string OfficeNotes { get; set; }
        public string CreditNotes { get; set; }
        public bool OverrideFreightCredit { get; set; }
        public decimal FreightCredit { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal PSTAmount { get; set; }
        public bool HST { get; set; }
        public bool PSTExempt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditItem> CreditItems { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
