//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreightCharge
    {
        public string AreaID { get; set; }
        public string Province { get; set; }
        public string PlaceName { get; set; }
        public decimal Charge { get; set; }
        public string Region { get; set; }
    
        public virtual State State { get; set; }
    }
}
