//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journal()
        {
            this.Campaigns = new HashSet<Campaign>();
        }
    
        public int JournalID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime DateStamp { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string Author { get; set; }
        public bool IsResolved { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string WhoInserted { get; set; }
        public string WhoUpdated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string AttachmentPath { get; set; }
        public int AssignedToId { get; set; }
        public Nullable<int> CampaignID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
        public virtual Campaign Campaign { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campaign> Campaigns { get; set; }
    }
}
