//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItem()
        {
            this.ShipmentItems = new HashSet<ShipmentItem>();
        }
    
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public double Quantity { get; set; }
        public int ProductId { get; set; }
        public double UnitPrice { get; set; }
        public double DiscountPercent { get; set; }
        public int LinePosition { get; set; }
        public bool ProductNotAvailable { get; set; }
        public string ProductNotAvailableDesc { get; set; }
        public bool NoGlobalDiscount { get; set; }
        public Nullable<int> OrderRackId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentItem> ShipmentItems { get; set; }
        public virtual OrderRack OrderRack { get; set; }
    }
}
