//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderRacks = new HashSet<OrderRack>();
        }
    
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int SalesPersonID { get; set; }
        public string PONumber { get; set; }
        public int OrderStatus { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<System.DateTime> QuoteExpiryDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> RequestedShipDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public int ShippingMethodID { get; set; }
        public string GlobalDiscountDesc { get; set; }
        public double GlobalDiscountPercent { get; set; }
        public string GlobalDiscount2Desc { get; set; }
        public double GlobalDiscount2Percent { get; set; }
        public string GlobalDiscount3Desc { get; set; }
        public double GlobalDiscount3Percent { get; set; }
        public string GlobalDiscount4Desc { get; set; }
        public double GlobalDiscount4Percent { get; set; }
        public string GlobalDiscount5Desc { get; set; }
        public double GlobalDiscount5Percent { get; set; }
        public bool CustomShippingCharge { get; set; }
        public decimal ShippingCharge { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal PSTAmount { get; set; }
        public bool PSTExempt { get; set; }
        public bool HST { get; set; }
        public int PaymentTypeID { get; set; }
        public int PaymentTermsID { get; set; }
        public string BillingName { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCountry { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingEmail { get; set; }
        public string OrderNotes { get; set; }
        public string OfficeNotes { get; set; }
        public Nullable<System.DateTime> PurchaseOrdersSentDate { get; set; }
        public Nullable<System.DateTime> ConfirmationSentDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public bool Approved { get; set; }
        public Nullable<int> ReceivedVia { get; set; }
        public Nullable<int> PurchaseOrderID { get; set; }
        public Nullable<System.Guid> BulkOrderKey { get; set; }
        public Nullable<int> BulkRackID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual supPaymentTerm supPaymentTerm { get; set; }
        public virtual supPaymentType supPaymentType { get; set; }
        public virtual supShippingMethod supShippingMethod { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRack> OrderRacks { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual ProductCatalogRack ProductCatalogRack { get; set; }
    }
}
