//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCollection
    {
        public int MainProductId { get; set; }
        public int LinkedProductId { get; set; }
        public int LinkedProductQuantity { get; set; }
    }
}
