//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCatalog()
        {
            this.ProductCatalogRacks = new HashSet<ProductCatalogRack>();
            this.Products = new HashSet<Product>();
            this.UserCatalogs = new HashSet<UserCatalog>();
            this.ProductCatalogShipDates = new HashSet<ProductCatalogShipDate>();
            this.States = new HashSet<State>();
            this.CampaignShipdates = new HashSet<CampaignShipdate>();
        }
    
        public int CatalogId { get; set; }
        public string CatalogName { get; set; }
        public string CustomerCatalogName { get; set; }
        public int CatalogGroupId { get; set; }
        public int CatalogClassId { get; set; }
        public string CatalogSeason { get; set; }
        public int CatalogYear { get; set; }
        public bool Active { get; set; }
        public bool ShowOnMyAccount { get; set; }
        public bool ShowBothItemNumbers { get; set; }
        public string PhotoPath { get; set; }
        public string PDFUrl { get; set; }
        public string OrderFormUrl { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ProductCatalogGroup ProductCatalogGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCatalogRack> ProductCatalogRacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCatalog> UserCatalogs { get; set; }
        public virtual ProductProgram ProductProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCatalogShipDate> ProductCatalogShipDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignShipdate> CampaignShipdates { get; set; }
    }
}
