//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProgramShipDate
    {
        public int ShipDateID { get; set; }
        public int ProgramID { get; set; }
        public System.DateTime ShipDate { get; set; }
        public System.DateTime OrderDeadlineDate { get; set; }
    
        public virtual ProductProgram ProductProgram { get; set; }
    }
}
