//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalogShipDate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCatalogShipDate()
        {
            this.CampaignShipdates = new HashSet<CampaignShipdate>();
        }
    
        public int ShipDateID { get; set; }
        public int CatalogID { get; set; }
        public System.DateTime ShipDate { get; set; }
        public Nullable<System.DateTime> OrderDeadlineDate { get; set; }
    
        public virtual ProductCatalog ProductCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignShipdate> CampaignShipdates { get; set; }
    }
}
