//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCatalogRack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductCatalogRack()
        {
            this.OrderRacks = new HashSet<OrderRack>();
            this.RackProducts = new HashSet<RackProduct>();
            this.ProductRackShipDates = new HashSet<ProductRackShipDate>();
            this.RackRacks = new HashSet<RackRack>();
            this.Photos = new HashSet<Photo>();
            this.Orders = new HashSet<Order>();
        }
    
        public int RackID { get; set; }
        public int CatalogID { get; set; }
        public string RackName { get; set; }
        public string RackDesc { get; set; }
        public bool AllowCustomization { get; set; }
        public string RackSize { get; set; }
        public Nullable<int> MinimumItems { get; set; }
        public Nullable<int> MaximumItems { get; set; }
        public Nullable<int> Available { get; set; }
        public string Dimensions { get; set; }
        public string Weight { get; set; }
        public string FilePath { get; set; }
        public int DisplayOrder { get; set; }
        public bool Active { get; set; }
        public int RackType { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual ProductCatalog ProductCatalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderRack> OrderRacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RackProduct> RackProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRackShipDate> ProductRackShipDates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RackRack> RackRacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photo> Photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
