//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RackRack
    {
        public int RackID { get; set; }
        public int ProductRackID { get; set; }
        public double DefaultQuantity { get; set; }
    
        public virtual ProductCatalogRack ProductRack { get; set; }
        public virtual ProductCatalogRack ParentRack { get; set; }
    }
}
