//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.ShipmentItems = new HashSet<ShipmentItem>();
        }
    
        public int ShipmentID { get; set; }
        public int AccountingInvoiceID { get; set; }
        public bool AccountingPosted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public int ShippingMethodId { get; set; }
        public string TrackingNumber { get; set; }
        public string ShipmentNotes { get; set; }
        public string OfficeNotes { get; set; }
        public string GlobalDiscountDesc { get; set; }
        public double GlobalDiscountPercent { get; set; }
        public string GlobalDiscount2Desc { get; set; }
        public double GlobalDiscount2Percent { get; set; }
        public string GlobalDiscount3Desc { get; set; }
        public double GlobalDiscount3Percent { get; set; }
        public string GlobalDiscount4Desc { get; set; }
        public double GlobalDiscount4Percent { get; set; }
        public string GlobalDiscount5Desc { get; set; }
        public double GlobalDiscount5Percent { get; set; }
        public bool CustomShippingCharge { get; set; }
        public decimal ShippingCharge { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal PSTAmount { get; set; }
        public bool HST { get; set; }
        public bool PSTExempt { get; set; }
        public Nullable<System.DateTime> InvoiceSentDate { get; set; }
    
        public virtual supShippingMethod supShippingMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentItem> ShipmentItems { get; set; }
    }
}
