//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCatalog
    {
        public int UserCatalogID { get; set; }
        public int UserID { get; set; }
        public int CatalogID { get; set; }
    
        public virtual ProductCatalog ProductCatalog { get; set; }
        public virtual User User { get; set; }
    }
}
