//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Journals = new HashSet<Journal>();
            this.Orders = new HashSet<Order>();
            this.UserAsscs = new HashSet<UserAssc>();
            this.UserCatalogs = new HashSet<UserCatalog>();
            this.UserStates = new HashSet<UserState>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public bool DefaultToPersonalJournals { get; set; }
        public bool DefaultToPersonalOrders { get; set; }
        public bool DefaultToPersonalShipments { get; set; }
        public string HighlightBackgroundColour { get; set; }
        public string HighlightForegroundColour { get; set; }
        public int SortPosition { get; set; }
        public bool ShowCampaigns { get; set; }
        public bool ShowSettings { get; set; }
        public bool ShowOtherMyJournals { get; set; }
        public bool ShowOtherMyOrders { get; set; }
        public bool ShowOtherMyShipments { get; set; }
        public bool CanSendNewsletters { get; set; }
        public bool CanCreateLabels { get; set; }
        public bool CanViewMyAccountActivity { get; set; }
        public bool CanDeleteCustomers { get; set; }
        public bool CanViewCustomerAssociations { get; set; }
        public bool CanMergeCustomers { get; set; }
        public bool CanEditOrders { get; set; }
        public bool CanDeleteOrders { get; set; }
        public bool CanEmailPrintExportOrders { get; set; }
        public bool CanApproveOrders { get; set; }
        public bool CanEditShipments { get; set; }
        public bool CanDeleteShipments { get; set; }
        public bool CanEmailPrintExportShipments { get; set; }
        public bool CanEditCreditMemos { get; set; }
        public bool CanDeleteCreditMemos { get; set; }
        public bool CanEmailPrintExportCreditMemos { get; set; }
        public bool CanOnlyViewAssignedAssociations { get; set; }
        public bool CanOnlyViewAssignedProvinces { get; set; }
        public bool CanOnlyViewAssignedCatalogs { get; set; }
        public bool CanOnlyViewOwnCustomers { get; set; }
        public string LogInName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journal> Journals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAssc> UserAsscs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCatalog> UserCatalogs { get; set; }
        public virtual User Users1 { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserState> UserStates { get; set; }
    }
}
