//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vmCustomerDetail
    {
        public int CustomerId { get; set; }
        public Nullable<int> AssociationID { get; set; }
        public string AsscDesc { get; set; }
        public string Class { get; set; }
        public string Company { get; set; }
        public string Contact { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public Nullable<int> LastOrderID { get; set; }
        public Nullable<System.DateTime> LastOrderDate { get; set; }
        public Nullable<int> JournalID { get; set; }
        public string State { get; set; }
        public string LastOrderDateFormatted { get; set; }
        public Nullable<int> StarRating { get; set; }
        public string Zip { get; set; }
    }
}
