//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAllOrder
    {
        public int OrderID { get; set; }
        public int SalesPersonID { get; set; }
        public string Company { get; set; }
        public string State { get; set; }
        public int CustomerID { get; set; }
        public string CustomerPhone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<double> OrderTotal { get; set; }
    }
}
