//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAsscwithCount
    {
        public int AssociationID { get; set; }
        public string Class { get; set; }
        public string AsscDesc { get; set; }
        public Nullable<int> CountCustomerId { get; set; }
        public string BlankCol { get; set; }
    }
}
