//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCatalogExport
    {
        public int ProductId { get; set; }
        public int CatalogId { get; set; }
        public Nullable<int> CatalogPageStart { get; set; }
        public Nullable<int> CatalogPageEnd { get; set; }
        public string SubCategoryDesc { get; set; }
        public string CustomerItemNumber { get; set; }
        public string InternalItemNumber { get; set; }
        public string ProductName { get; set; }
        public string Size { get; set; }
        public int ItemsPerPackage { get; set; }
        public int PackagesPerUnit { get; set; }
        public double UnitWeight { get; set; }
        public double UnitSize { get; set; }
        public double RedbudUnitCost { get; set; }
        public double UnitPrice { get; set; }
        public string UPCCode { get; set; }
        public string SuggestedPackageRetail { get; set; }
        public string SupplierName { get; set; }
        public int WarehouseLocation { get; set; }
    }
}
