//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCreditItem
    {
        public int CreditItemId { get; set; }
        public int CreditID { get; set; }
        public double Units { get; set; }
        public double PackagesPerUnit { get; set; }
        public string SubCategoryDesc { get; set; }
        public string ItemNumber { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Size { get; set; }
        public int ItemsPerPackage { get; set; }
        public decimal EachPrice { get; set; }
        public Nullable<double> Total { get; set; }
        public int Checkbox { get; set; }
        public Nullable<int> CatalogPageStart { get; set; }
    }
}
