//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCreditItemSelector
    {
        public int ProductId { get; set; }
        public int CreditQuantity { get; set; }
        public double QuantityShipped { get; set; }
        public int PackagesPerUnit { get; set; }
        public int ItemsPerPackage { get; set; }
        public string ItemNumber { get; set; }
        public string ProductName { get; set; }
        public string Size { get; set; }
        public double UnitPrice { get; set; }
        public double DiscountPercent { get; set; }
        public int ShipmentId { get; set; }
    }
}
