//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCustomerUnshippedOrder
    {
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> RequestedShipDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShippingName { get; set; }
        public string ShippedTo { get; set; }
        public Nullable<double> Total { get; set; }
    }
}
