//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwInvoicePostBatch
    {
        public int BatchID { get; set; }
        public System.DateTime BatchDate { get; set; }
        public int ShipmentID { get; set; }
        public Nullable<System.DateTime> DateShipped { get; set; }
        public int OrderID { get; set; }
        public string Company { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCountry { get; set; }
        public bool InvoicePrinted { get; set; }
        public int InvoiceCopies { get; set; }
        public bool InvoiceEmailed { get; set; }
        public string EmailAddress { get; set; }
        public bool InvoicePosted { get; set; }
        public decimal InvoiceTotal { get; set; }
        public string InvoicePostedMessage { get; set; }
    }
}
