//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMyOrders_OLD
    {
        public int OrderID { get; set; }
        public string Company { get; set; }
        public string State { get; set; }
        public int CustomerID { get; set; }
        public string CustomerPhone { get; set; }
        public Nullable<System.DateTime> ConfirmationSentDate { get; set; }
        public Nullable<System.DateTime> PurchaseOrdersSentDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<double> OrderTotal { get; set; }
        public Nullable<System.DateTime> RequestedShipDate { get; set; }
        public int OrderStatus { get; set; }
        public int SalesPersonID { get; set; }
        public string SalesPerson { get; set; }
        public string HighlightBackgroundColour { get; set; }
        public string HighlightForegroundColour { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<System.DateTime> QuoteExpiryDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public Nullable<int> CatalogId { get; set; }
        public string CatalogName { get; set; }
    }
}
