//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMyAccountActivityLog
    {
        public int CustomerId { get; set; }
        public string Company { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public string SessionId { get; set; }
        public string CustomerEmail { get; set; }
        public string ActivityDesc { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public Nullable<int> StarRating { get; set; }
    }
}
