//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMyShipments2
    {
        public int ShipmentID { get; set; }
        public int CustomerID { get; set; }
        public int OrderId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> InvoiceSentDate { get; set; }
        public string ShippingMethodDesc { get; set; }
        public string ShippingName { get; set; }
        public string Province { get; set; }
        public string OfficeNotes { get; set; }
        public Nullable<double> ShipmentTotal { get; set; }
    }
}
