//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwOrderItem
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public double Quantity { get; set; }
        public string SubCategoryDesc { get; set; }
        public string ItemNumber { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string Size { get; set; }
        public int ItemsPerPackage { get; set; }
        public int PackagesPerUnit { get; set; }
        public double UnitPrice { get; set; }
        public double Total { get; set; }
        public double DiscountPercent { get; set; }
        public bool ProductNotAvailable { get; set; }
        public Nullable<double> UnshippedQuantity { get; set; }
        public int Checkbox { get; set; }
        public Nullable<int> CatalogPageStart { get; set; }
        public string ProductNotAvailableDesc { get; set; }
    }
}
