//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProduct
    {
        public int ProductId { get; set; }
        public int CatalogId { get; set; }
        public int Quantity { get; set; }
        public string PageNumber { get; set; }
        public string CategoryDesc { get; set; }
        public string SubCategoryDesc { get; set; }
        public string ItemNumber { get; set; }
        public string ItemNumberInternal { get; set; }
        public string ProductName { get; set; }
        public string Size { get; set; }
        public int ItemsPerPackage { get; set; }
        public int PackagesPerUnit { get; set; }
        public double UnitPrice { get; set; }
        public Nullable<int> CatalogPageStart { get; set; }
        public bool ProductNotAvailable { get; set; }
        public string ProdNotAvailDesc { get; set; }
        public bool NewItem { get; set; }
    }
}
