//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRptPackingSlip
    {
        public int ShipmentID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ShipmentNotes { get; set; }
        public int OrderItemId { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> CatalogPageStart { get; set; }
        public string PageNumber { get; set; }
        public string ItemNumber { get; set; }
        public double Quantity { get; set; }
        public string QuantityDesc { get; set; }
        public string ProductName { get; set; }
        public string ProductNameAndSize { get; set; }
        public int ItemsPerPackage { get; set; }
        public int PackagesPerUnit { get; set; }
        public Nullable<System.DateTime> RequestedShipDate { get; set; }
        public string CatalogName { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingCityStateZip { get; set; }
        public string UPCCode { get; set; }
        public string SuggestedPackageRetail { get; set; }
        public double QuantityOrdered { get; set; }
        public double QuantityBackOrdered { get; set; }
        public bool ProductNotAvailable { get; set; }
        public string ProductNotAvailableDesc { get; set; }
        public string ItemNumberInternal { get; set; }
        public int ProductId { get; set; }
    }
}
