//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRptProductCollection
    {
        public int MainProductId { get; set; }
        public int LinkedProductId { get; set; }
        public int LinkedProductQuantity { get; set; }
        public string QuantityDesc { get; set; }
        public string PageNumber { get; set; }
        public string ItemNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductNameAndSize { get; set; }
        public string ProductDesc { get; set; }
        public int SubCategoryID { get; set; }
        public string SubCategoryDesc { get; set; }
        public int ItemsPerPackage { get; set; }
        public int PackagesPerUnit { get; set; }
        public string Size { get; set; }
        public string UPCCode { get; set; }
        public string SuggestedPackageRetail { get; set; }
        public Nullable<int> CatalogPageStart { get; set; }
        public Nullable<int> CatalogPageEnd { get; set; }
    }
}
