//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRptOrderConfirmation
    {
        public int OrderItemId { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> CatalogPageStart { get; set; }
        public string PageNumber { get; set; }
        public string ItemNumber { get; set; }
        public double Quantity { get; set; }
        public string QuantityDesc { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductNameAndSize { get; set; }
        public int ItemsPerPackage { get; set; }
        public int PackagesPerUnit { get; set; }
        public double EachPrice { get; set; }
        public double UnitPrice { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public string OrderNotes { get; set; }
        public Nullable<System.DateTime> RequestedShipDate { get; set; }
        public string CatalogName { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PaymentTypeDesc { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingCityStateZip { get; set; }
        public string BillingName { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCityStateZip { get; set; }
        public string BillingCountry { get; set; }
        public string UPCCode { get; set; }
        public string SuggestedPackageRetail { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> DiscountTotal { get; set; }
        public Nullable<decimal> DiscountedSubTotal { get; set; }
        public decimal ShippingCharge { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal PSTAmount { get; set; }
        public bool PSTExempt { get; set; }
        public bool HST { get; set; }
        public string SalesPerson { get; set; }
        public string ShippingMethodDesc { get; set; }
        public string PaymentTermsDesc { get; set; }
        public bool ProductNotAvailable { get; set; }
        public string ProductNotAvailableDesc { get; set; }
        public string GlobalDiscountDesc { get; set; }
        public double GlobalDiscountPercent { get; set; }
        public string GlobalDiscount2Desc { get; set; }
        public double GlobalDiscount2Percent { get; set; }
        public string GlobalDiscount3Desc { get; set; }
        public double GlobalDiscount3Percent { get; set; }
        public string GlobalDiscount4Desc { get; set; }
        public double GlobalDiscount4Percent { get; set; }
        public string GlobalDiscount5Desc { get; set; }
        public double GlobalDiscount5Percent { get; set; }
        public double DiscountPercent { get; set; }
    }
}
