//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRptCreditMemo
    {
        public int CreditID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string OfficeNotes { get; set; }
        public string CreditNotes { get; set; }
        public decimal FreightCredit { get; set; }
        public decimal GSTAmount { get; set; }
        public decimal PSTAmount { get; set; }
        public double Units { get; set; }
        public string QuantityDesc { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductNameAndSize { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<int> CatalogPageStart { get; set; }
        public string PageNumber { get; set; }
        public int ItemsPerPackage { get; set; }
        public double PackagesPerUnit { get; set; }
        public int CatalogId { get; set; }
        public string CatalogName { get; set; }
        public string BillingName { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingCountry { get; set; }
        public string BillingCityStateZip { get; set; }
        public decimal EachPrice { get; set; }
        public Nullable<decimal> ExtendedPrice { get; set; }
        public string ShippingName { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingCityStateZip { get; set; }
        public string UPCCode { get; set; }
        public string SuggestedPackageRetail { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public double Quantity { get; set; }
    }
}
