//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Redbud.BL.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwShipmentCatalog
    {
        public int ShipmentId { get; set; }
        public int CatalogId { get; set; }
        public string CatalogName { get; set; }
        public int CatalogClassId { get; set; }
        public string CatalogSeason { get; set; }
        public int CatalogYear { get; set; }
        public bool Active { get; set; }
        public bool ShowOnMyAccount { get; set; }
        public bool ShowBothItemNumbers { get; set; }
        public string PDFUrl { get; set; }
    }
}
